### ISSUE TITLE
Your Work Is Appreciated!

### ISSUE THREAD

**Issue by 509dave16** [compactd/slothdb#9]
Hey! I just wanted to say thank you for writing this package. I have only just recently dived into PouchDB. I have been tinkering around with my own "orm-like" wrapper around the side-loaded data from `relational-pouch` in order to better handle accessing related entities. And I was looking to add schema enforcement. Then I stumbled across your repository. I plan to use `relational-pouch` and SlothDB together. If you would like any feedback, help with docs, etc..., let me know. I found your other work on Github interesting too. Really like the doc generator that you're using. And that you're using typescript heavily.

Best Regards,
David Fall

**Comment by vinz243** [comment]
Hey! Thanks for the feedback it's nice to see other people using it! For the schema enforcement for now it's really basic only annotated fields are going to be saved to database. I was thinking that it should be possible to enforce specific validation rules using class-validator and class-sanitizer, by fetching the property descriptor in the SlothRel decorator, and using it to validate/satinize before actually updating property value.
I personnally don't use relational-pouch and I don't think it's possible to use it with slothdb, unless you rewrite the SlothDatabase code. To describe relations slothdb relies on hierarchical ids like `library/grr-martin/a-song-of-ice-and-fire` and on splitting entities into two separate databases, which relational-pouch won't do.
Any feedback is always welcome, and I'm sure there are a lot of docs that are poorly written or barely understandable that would need to be rewritten. 
Also once you started using typescript, it's hard to go back
